kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 32080
    hostPort: 80
    listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
- role: worker
- role: worker
