apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: loqu
spec:
  rules:
  - host: loqu.example.com
    http:
      paths:
      - backend:
          serviceName: loqu
          servicePort: 80
        path: /
