name: Trigger release

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Name of target release branch'
        default: 'release-0.1.x'
        required: true

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Merge master -> {target}
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: master
          target_branch: ${{ github.event.inputs.target }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
